import json
import urllib.request
import urllib.parse
import base64
import os

GITHUB_TOKEN = os.environ.get('GH_TOKEN', '')
REPO = os.environ.get('GITHUB_REPO', 'goldenjackets-community/golden-jackets-brazil')

def lambda_handler(event, context):
    cors = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS'
    }

    if event.get('requestContext', {}).get('http', {}).get('method') == 'OPTIONS':
        return {'statusCode': 200, 'headers': cors, 'body': ''}

    try:
        body = json.loads(event.get('body', '{}'))
        name = body['name']
        city = body['city']
        state = body['state']
        date = body['date']
        linkedin = body['linkedin']
        email = body.get('email', '')
        member_type = body.get('memberType', 'golden')
        photo_b64 = body.get('photo', '')
        photo_name = body.get('photoName', '')
        consent = body.get('consentAccepted', False)
        consent_date = body.get('consentDate', '')

        # Determine file name for photo
        safe_name = name.lower().replace(' ', '-').replace('.', '')
        photo_ext = photo_name.split('.')[-1] if photo_name else 'jpg'
        photo_path = f'assets/members/{safe_name}.{photo_ext}'

        # Create branch name
        branch = f'add-member-{safe_name}'

        # Get default branch SHA
        req = urllib.request.Request(
            f'https://api.github.com/repos/{REPO}/git/ref/heads/main',
            headers={'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
        )
        resp = urllib.request.urlopen(req)
        sha = json.loads(resp.read())['object']['sha']

        # Create branch
        data = json.dumps({'ref': f'refs/heads/{branch}', 'sha': sha}).encode()
        req = urllib.request.Request(
            f'https://api.github.com/repos/{REPO}/git/refs',
            data=data,
            headers={'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
        )
        try:
            urllib.request.urlopen(req)
        except urllib.error.HTTPError as e:
            if e.code == 422:  # branch exists
                pass
            else:
                raise

        # Upload photo if provided
        if photo_b64:
            data = json.dumps({
                'message': f'Add photo for {name}',
                'content': photo_b64,
                'branch': branch
            }).encode()
            req = urllib.request.Request(
                f'https://api.github.com/repos/{REPO}/contents/{photo_path}',
                data=data,
                method='PUT',
                headers={'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
            )
            urllib.request.urlopen(req)

        # Always create an application file (ensures branch has a commit for PR)
        app_data = json.dumps({
            'name': name, 'city': city, 'state': state, 'date': date,
            'linkedin': linkedin, 'email': email, 'memberType': member_type,
            'photo': photo_path if photo_b64 else '', 'consent': consent, 'consentDate': consent_date
        }, indent=2)
        app_content = base64.b64encode(app_data.encode()).decode()
        data = json.dumps({
            'message': f'Application: {name}',
            'content': app_content,
            'branch': branch
        }).encode()
        req = urllib.request.Request(
            f'https://api.github.com/repos/{REPO}/contents/applications/{safe_name}.json',
            data=data,
            method='PUT',
            headers={'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
        )
        urllib.request.urlopen(req)

        # Create PR
        pr_title = f'New Member: {name}'
        pr_body = f'''## New Member Application

**Name:** {name}
**City:** {city}
**State:** {state}
**Certified Date:** {date}
**LinkedIn:** {linkedin}
**Email:** {email}
**Type:** {member_type}
**Photo:** {photo_path}
**Consent:** {consent} ({consent_date})

---
_Auto-generated by the Golden Jackets apply form._
'''

        data = json.dumps({
            'title': pr_title,
            'body': pr_body,
            'head': branch,
            'base': 'main'
        }).encode()
        req = urllib.request.Request(
            f'https://api.github.com/repos/{REPO}/pulls',
            data=data,
            headers={'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
        )
        resp = urllib.request.urlopen(req)
        pr_data = json.loads(resp.read())

        return {
            'statusCode': 200,
            'headers': cors,
            'body': json.dumps({'message': f'Application submitted! PR #{pr_data["number"]} created.', 'pr': pr_data['html_url']})
        }

    except Exception as e:
        return {
            'statusCode': 500,
            'headers': cors,
            'body': json.dumps({'error': str(e)})
        }
